// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs password-generator`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "encrypt-zip",
    "icon": "🔒",
    "name": {
      "en": "Encrypt ZIP",
      "ja": "Zip暗号化",
      "zh": "加密 ZIP",
      "de": "ZIP verschlüsseln",
      "es": "Cifrar ZIP"
    },
    "desc": {
      "en": "Create a password-protected (AES-256) .zip.",
      "ja": "パスワード付き(AES-256)の .zip を作成。",
      "zh": "创建带密码(AES-256)的 .zip。",
      "de": "Ein passwortgeschütztes (AES-256) .zip erstellen.",
      "es": "Crea un .zip protegido con contraseña (AES-256)."
    }
  },
  {
    "slug": "decode-certificate",
    "icon": "📜",
    "name": {
      "en": "Decode Certificate",
      "ja": "証明書デコード",
      "zh": "解码证书",
      "de": "Zertifikat dekodieren",
      "es": "Decodificar certificado"
    },
    "desc": {
      "en": "Decode X.509 certificates and CSRs — no server ever sees the private material.",
      "ja": "X.509証明書とCSRをデコード。サーバーに送信しないため機密情報が漏れない。",
      "zh": "解码 X.509 证书和 CSR — 敏感内容永远不会发送到服务器。",
      "de": "Dekodiert X.509-Zertifikate und CSRs — sensible Daten verlassen nie den Browser.",
      "es": "Decodifica certificados X.509 y CSR — el material sensible nunca sale del navegador."
    }
  },
  {
    "slug": "file-hash",
    "icon": "#️⃣",
    "name": {
      "en": "File Hash",
      "ja": "ファイルハッシュ計算",
      "zh": "文件哈希",
      "de": "Datei-Hash",
      "es": "Hash de archivo"
    },
    "desc": {
      "en": "Compute SHA-256, SHA-1 or MD5 for a file and compare against an expected value.",
      "ja": "ファイルのSHA-256・SHA-1・MD5を計算し、期待値と照合。",
      "zh": "计算文件的 SHA-256、SHA-1 或 MD5，并与预期值比对。",
      "de": "Berechnet SHA-256, SHA-1 oder MD5 einer Datei und vergleicht mit einem erwarteten Wert.",
      "es": "Calcula SHA-256, SHA-1 o MD5 de un archivo y lo compara con un valor esperado."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'password-generator';
